import chromadb
import uuid
import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

class VectorStore:
    """
    Manages the ChromaDB vector database.
    This database stores our text chunks alongside their dense vector embeddings,
    allowing us to perform blazing-fast semantic searches.
    """
    
    def __init__(self, db_path: str = "./data/chroma_db"):
        """
        Initializes the ChromaDB client.
        We use a PersistentClient so data survives application restarts.
        
        Args:
            db_path (str): The local directory where ChromaDB will store its files.
        """
        self.db_path = db_path
        self.client = chromadb.PersistentClient(path=db_path)
        
    def get_or_create_collection(self, repo_id: str):
        """
        Retrieves or creates a collection for a specific repository.
        By isolating repositories into their own collections, we ensure that
        queries only search within the relevant codebase.
        
        Args:
            repo_id (str): A unique identifier for the repository (e.g., its name or DB ID).
        """
        # ChromaDB collection names must be valid alphanumeric strings without special characters.
        # We replace any invalid chars with underscores.
        safe_name = "".join([c if c.isalnum() else "_" for c in repo_id])
        return self.client.get_or_create_collection(name=safe_name)

    def insert_chunks(self, repo_id: str, chunks: List[Dict]):
        """
        Inserts embedded chunks into the vector database.
        
        Args:
            repo_id (str): The repository identifier.
            chunks (List[Dict]): Chunks generated by our CodeChunker and CodeEmbedder.
                                 Must contain 'content', 'metadata', and 'embedding' keys.
        """
        if not chunks:
            logger.warning("No chunks provided for insertion.")
            return
            
        collection = self.get_or_create_collection(repo_id)
        
        ids = []
        embeddings = []
        documents = []
        metadatas = []
        
        for chunk in chunks:
            # We generate a unique ID for every single chunk
            chunk_id = str(uuid.uuid4())
            ids.append(chunk_id)
            
            embeddings.append(chunk["embedding"])
            documents.append(chunk["content"])
            
            # ChromaDB requires metadata values to be str, int, float, or bool.
            # We ensure nested dicts or complex types are avoided or casted to strings.
            safe_metadata = {}
            for k, v in chunk.get("metadata", {}).items():
                if isinstance(v, (str, int, float, bool)):
                    safe_metadata[k] = v
                else:
                    safe_metadata[k] = str(v)
            metadatas.append(safe_metadata)
            
        # Batch insert into ChromaDB
        collection.add(
            ids=ids,
            embeddings=embeddings,
            documents=documents,
            metadatas=metadatas
        )
        logger.info(f"Successfully inserted {len(chunks)} chunks into collection {repo_id}")

    def semantic_search(self, repo_id: str, query_embedding: List[float], n_results: int = 5) -> List[Dict[str, Any]]:
        """
        Performs a semantic search against the vector database using a query embedding.
        Uses Cosine Similarity (default in Chroma) to find the closest matches in vector space.
        
        Args:
            repo_id (str): The repository identifier to search within.
            query_embedding (List[float]): The 384-dimensional vector of the user's question.
            n_results (int): How many top results to retrieve.
            
        Returns:
            List[Dict[str, Any]]: A list of results containing the document, metadata, and distance.
        """
        try:
            collection = self.client.get_collection(name="".join([c if c.isalnum() else "_" for c in repo_id]))
        except ValueError:
            logger.error(f"Collection for {repo_id} does not exist.")
            return []
            
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results
        )
        
        # Format the results cleanly
        formatted_results = []
        if results and results["documents"] and len(results["documents"]) > 0:
            for i in range(len(results["documents"][0])):
                formatted_results.append({
                    "id": results["ids"][0][i],
                    "content": results["documents"][0][i],
                    "metadata": results["metadatas"][0][i],
                    "distance": results["distances"][0][i] # Lower distance = higher similarity
                })
                
        return formatted_results
