import logging
from typing import List, Dict, Union
from sentence_transformers import SentenceTransformer

logger = logging.getLogger(__name__)

class CodeEmbedder:
    """
    Generates dense vector embeddings for text and code chunks using SentenceTransformers.
    These vectors capture the semantic meaning of the code, allowing for powerful
    Retrieval-Augmented Generation (RAG).
    """
    
    def __init__(self, model_name: str = 'all-MiniLM-L6-v2'):
        """
        Args:
            model_name (str): The HuggingFace model to use. 'all-MiniLM-L6-v2' is a 
                              fast, lightweight model perfect for local execution.
        """
        logger.info(f"Loading embedding model: {model_name}. This might take a moment on first run...")
        # SentenceTransformer automatically downloads the model on the first run
        self.model = SentenceTransformer(model_name)
        self.vector_dim = self.model.get_sentence_embedding_dimension()
        logger.info(f"Model loaded. Vector dimension: {self.vector_dim}")

    def generate_embeddings(self, texts: Union[str, List[str]]) -> List[List[float]]:
        """
        Generates embeddings for a single string or a list of strings.
        
        Args:
            texts (Union[str, List[str]]): The text(s) to embed.
            
        Returns:
            List[List[float]]: A list of embedding vectors (floats).
        """
        if isinstance(texts, str):
            texts = [texts]
            
        # encode() returns a numpy array, we convert to list of floats for easier DB insertion
        embeddings = self.model.encode(texts, convert_to_numpy=True)
        return [embedding.tolist() for embedding in embeddings]

    def embed_chunks(self, chunks: List[Dict]) -> List[Dict]:
        """
        Takes a list of chunk dictionaries, generates embeddings for their content,
        and returns the chunks with the new 'embedding' key added.
        
        Args:
            chunks (List[Dict]): Chunks generated by CodeChunker.
            
        Returns:
            List[Dict]: The same chunks, now containing their vector representations.
        """
        if not chunks:
            return []
            
        texts_to_embed = [chunk["content"] for chunk in chunks]
        embeddings = self.generate_embeddings(texts_to_embed)
        
        for i, chunk in enumerate(chunks):
            chunk["embedding"] = embeddings[i]
            
        return chunks
